import React from 'react';

const page = () => {
    return (
        <div>
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
            buy <br />
        </div>
    );
};

export default page;